apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-116
  labels:
    app: nginx-116
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-116
  template:
    metadata:
      labels:
        app: nginx-116
    spec:
      containers:
        - name: nginx
          image: quay.io/jpacker/nginx:1.16.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
