apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-clb
  name: myclb
spec:
  type: LoadBalancer
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx-116
